### ISSUE TITLE
get_block 返回 proof 信息

### ISSUE THREAD

**Issue by Pencil-Yao** [cita-cloud/controller#143]
目前get_block仅返回压缩块的内容，缺少proof信息，会涉及到cita_cloud_proto的修改

bft：可以返回投票信息以及签名
raft：可以返回投票信息，或不返回留空

**Comment by rink1969** [comment]
1. 单独加一个接口。
2. 把get block with detail 的返回结果里加上proof。这个要跟产品确认一下他们是否已经使用该接口了。

**Comment by JLerxky** [comment]
目前proof的结构在共识中,无法由controller或cli解析;
共识将proof解析成一个兼容结构体, 该结构体放在proto中, cli解析

**Comment by rink1969** [comment]
fixed by https://github.com/cita-cloud/cloud-cli/pull/43
