### ISSUE TITLE
交易池内交易查询的功能

### ISSUE THREAD

**Issue by Pencil-Yao** [cita-cloud/controller#144]
提供查询交易池内交易的接口，会涉及到`cita_cloud_proto`的修改

可以帮助确认节点是否接收到交易，有助于分析交易上链的情况

**Comment by rink1969** [comment]
GetTransaction加一个新的错误信息，对应交易已经在本节点的交易池，但是还没有打包尽快。

**Comment by rink1969** [comment]
fixed by https://github.com/cita-cloud/controller/pull/151
